import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
  user,
  revenue,
  notifications,
}: Readonly<{
  children: React.ReactNode;
  user: React.ReactNode;
  revenue: React.ReactNode;
  notifications: React.ReactNode;
}>) {
  return (
    <>
      {children}
      {revenue}
      {user}
      {notifications}
    </>
  );
}
