export const metadata = {
  title: "About Me",
  description: "Generated by create next app",
};
export default function About() {
    return(
      <div className="">
        About
      </div>
    )
  }
  