import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header
        style={{backgroundColor:"lightblue", color:"black"}}
        ><p>Header</p> </header>
        {children}
        <footer
        style={{backgroundColor:"lightgreen", color:"black"}}
        ><p>Footer</p></footer>
        </body>
    </html>
  );
}
